# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='caption',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
