# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_auto_20160812_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=b'images/presentations/thumbnails/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='customimage',
            options={'ordering': ['image']},
        ),
    ]
